export enum DomainErrorCode {
  INVALID_TIME = "INVALID_TIME",
  PAST_DATE = "PAST_DATE",
  FUTURE_DATE = "FUTURE_DATE",
  DATE_TOO_LATE = "DATE_TOO_LATE",
  INVALID_DATE = "INVALID_DATE",
  INVALID_WORKDAY = "INVALID_WORKDAY",
  INVALID_WORK_SHIFT = "INVALID_WORK_SHIFT",
  MISMATCH_BARBER = "MISMATCH_BARBER",
  MISMATCH_WORKDAY = "MISMATCH_WORKDAY",
}
